"""directory tables"""
from alembic import op
import sqlalchemy as sa
revision = "0003_directory"; down_revision = "0002_identity_audit"; branch_labels = None; depends_on = None
def upgrade() -> None:
    op.create_table("venues", sa.Column("name",sa.String(120),nullable=False),sa.Column("timezone",sa.String(64),nullable=False),sa.Column("weekday_open_time",sa.Time(),nullable=False),sa.Column("weekday_close_time",sa.Time(),nullable=False),sa.Column("weekend_open_time",sa.Time(),nullable=False),sa.Column("weekend_close_time",sa.Time(),nullable=False),sa.Column("id",sa.String(36),primary_key=True),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.Column("version",sa.Integer(),nullable=False))
    common=[sa.Column("id",sa.String(36),primary_key=True),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.Column("version",sa.Integer(),nullable=False)]
    op.create_table("courts",sa.Column("venue_id",sa.String(36),sa.ForeignKey("venues.id"),nullable=False),sa.Column("code",sa.String(32),nullable=False,unique=True),sa.Column("name",sa.String(120),nullable=False),sa.Column("is_active",sa.Boolean(),nullable=False),sa.Column("notes",sa.Text()),*common)
    op.create_table("coach_profiles",sa.Column("name",sa.String(120),nullable=False),sa.Column("phone",sa.String(32)),sa.Column("specialties",sa.Text()),sa.Column("is_active",sa.Boolean(),nullable=False),*[sa.Column("id",sa.String(36),primary_key=True),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.Column("version",sa.Integer(),nullable=False)])
    op.create_table("students",sa.Column("name",sa.String(120),nullable=False),sa.Column("gender",sa.String(20)),sa.Column("birth_date",sa.Date()),sa.Column("phone",sa.String(32)),sa.Column("level_tags",sa.Text()),sa.Column("is_active",sa.Boolean(),nullable=False),sa.Column("notes",sa.Text()),*[sa.Column("id",sa.String(36),primary_key=True),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.Column("version",sa.Integer(),nullable=False)])
    op.create_table("guardians",sa.Column("name",sa.String(120),nullable=False),sa.Column("phone",sa.String(32),nullable=False),sa.Column("wechat_note",sa.String(120)),sa.Column("notes",sa.Text()),*[sa.Column("id",sa.String(36),primary_key=True),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.Column("version",sa.Integer(),nullable=False)])
    op.create_table("student_guardians",sa.Column("student_id",sa.String(36),sa.ForeignKey("students.id",ondelete="CASCADE"),primary_key=True),sa.Column("guardian_id",sa.String(36),sa.ForeignKey("guardians.id",ondelete="CASCADE"),primary_key=True),sa.Column("relationship_label",sa.String(40),nullable=False),sa.Column("is_primary_contact",sa.Boolean(),nullable=False))
    op.create_table("walk_in_customers",sa.Column("display_name",sa.String(120),nullable=False),sa.Column("phone",sa.String(32)),sa.Column("wechat_note",sa.String(120)),sa.Column("notes",sa.Text()),*[sa.Column("id",sa.String(36),primary_key=True),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.Column("version",sa.Integer(),nullable=False)])
def downgrade() -> None:
    for n in ["walk_in_customers","student_guardians","guardians","students","coach_profiles","courts","venues"]: op.drop_table(n)
