"""enrollment and lesson ledger"""
from alembic import op
import sqlalchemy as sa
revision="0006_enrollment_ledger";down_revision="0005_fixed_classes";branch_labels=None;depends_on=None
def upgrade()->None:
    op.create_table("enrollments",sa.Column("student_id",sa.String(36),sa.ForeignKey("students.id"),nullable=False),sa.Column("fixed_class_id",sa.String(36),sa.ForeignKey("fixed_classes.id"),nullable=False),sa.Column("enrolled_on",sa.Date(),nullable=False),sa.Column("purchased_units",sa.Integer(),nullable=False),sa.Column("unit_price",sa.Numeric(12,2),nullable=False),sa.Column("suggested_receivable",sa.Numeric(12,2),nullable=False),sa.Column("actual_receivable",sa.Numeric(12,2),nullable=False),sa.Column("is_midterm",sa.Boolean(),nullable=False),sa.Column("price_adjustment_reason",sa.Text()),sa.Column("status",sa.String(30),nullable=False),sa.Column("notes",sa.Text()),sa.Column("id",sa.String(36),primary_key=True),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.Column("version",sa.Integer(),nullable=False))
    op.create_table("lesson_unit_ledgers",sa.Column("owner_type",sa.String(30),nullable=False),sa.Column("owner_id",sa.String(36),nullable=False),sa.Column("change_type",sa.String(40),nullable=False),sa.Column("delta",sa.Integer(),nullable=False),sa.Column("balance_before",sa.Integer(),nullable=False),sa.Column("balance_after",sa.Integer(),nullable=False),sa.Column("source_type",sa.String(40),nullable=False),sa.Column("source_id",sa.String(36),nullable=False),sa.Column("reason",sa.Text()),sa.Column("status",sa.String(20),nullable=False),sa.Column("reversal_of_id",sa.String(36),sa.ForeignKey("lesson_unit_ledgers.id")),sa.Column("operated_by",sa.String(36),nullable=False),sa.Column("operated_at",sa.DateTime(timezone=True),nullable=False),sa.Column("idempotency_key",sa.String(128),nullable=False,unique=True),sa.Column("id",sa.String(36),primary_key=True))
    op.create_table("attendance_records",sa.Column("class_session_id",sa.String(36),sa.ForeignKey("class_sessions.id"),nullable=False),sa.Column("student_id",sa.String(36),sa.ForeignKey("students.id"),nullable=False),sa.Column("enrollment_id",sa.String(36),sa.ForeignKey("enrollments.id"),nullable=False),sa.Column("status",sa.String(30),nullable=False),sa.Column("deduct_units",sa.Integer(),nullable=False),sa.Column("grants_makeup",sa.Boolean(),nullable=False),sa.Column("lesson_ledger_id",sa.String(36),sa.ForeignKey("lesson_unit_ledgers.id")),sa.Column("decision_note",sa.Text()),sa.Column("id",sa.String(36),primary_key=True),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.Column("version",sa.Integer(),nullable=False),sa.UniqueConstraint("class_session_id","student_id",name="uq_session_student_attendance"))
    op.create_table("makeup_records",sa.Column("student_id",sa.String(36),sa.ForeignKey("students.id"),nullable=False),sa.Column("origin_attendance_id",sa.String(36),sa.ForeignKey("attendance_records.id"),nullable=False,unique=True),sa.Column("target_class_session_id",sa.String(36),sa.ForeignKey("class_sessions.id")),sa.Column("status",sa.String(30),nullable=False),sa.Column("deduct_units",sa.Integer()),sa.Column("created_by",sa.String(36),nullable=False),sa.Column("completed_at",sa.DateTime(timezone=True)),sa.Column("notes",sa.Text()),sa.Column("id",sa.String(36),primary_key=True),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.Column("version",sa.Integer(),nullable=False))
def downgrade()->None:
    for n in ["makeup_records","attendance_records","lesson_unit_ledgers","enrollments"]:op.drop_table(n)
