"""venue bookings and events"""
from alembic import op
import sqlalchemy as sa
revision="0008_bookings_events";down_revision="0007_private_lessons";branch_labels=None;depends_on=None
def upgrade()->None:
    op.create_table("venue_price_rules",sa.Column("name",sa.String(120),nullable=False),sa.Column("day_type",sa.String(20),nullable=False),sa.Column("effective_from",sa.Date()),sa.Column("effective_to",sa.Date()),sa.Column("time_start",sa.Time(),nullable=False),sa.Column("time_end",sa.Time(),nullable=False),sa.Column("price_per_court_hour",sa.Numeric(12,2),nullable=False),sa.Column("priority",sa.Integer(),nullable=False),sa.Column("is_active",sa.Boolean(),nullable=False),sa.Column("id",sa.String(36),primary_key=True),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.Column("version",sa.Integer(),nullable=False))
    op.create_table("venue_bookings",sa.Column("customer_id",sa.String(36),sa.ForeignKey("walk_in_customers.id"),nullable=False),sa.Column("starts_at",sa.DateTime(timezone=True),nullable=False),sa.Column("ends_at",sa.DateTime(timezone=True),nullable=False),sa.Column("court_ids_csv",sa.Text(),nullable=False),sa.Column("price_rule_id",sa.String(36),sa.ForeignKey("venue_price_rules.id")),sa.Column("suggested_receivable",sa.Numeric(12,2),nullable=False),sa.Column("actual_receivable",sa.Numeric(12,2),nullable=False),sa.Column("price_adjustment_reason",sa.Text()),sa.Column("payment_status",sa.String(30),nullable=False),sa.Column("status",sa.String(30),nullable=False),sa.Column("schedule_entry_id",sa.String(36),sa.ForeignKey("schedule_entries.id")),sa.Column("notes",sa.Text()),sa.Column("id",sa.String(36),primary_key=True),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.Column("version",sa.Integer(),nullable=False))
    op.create_table("temporary_events",sa.Column("event_type",sa.String(60),nullable=False),sa.Column("name",sa.String(160),nullable=False),sa.Column("starts_at",sa.DateTime(timezone=True),nullable=False),sa.Column("ends_at",sa.DateTime(timezone=True),nullable=False),sa.Column("court_ids_csv",sa.Text(),nullable=False),sa.Column("coach_id",sa.String(36)),sa.Column("coach_fee",sa.Numeric(12,2),nullable=False),sa.Column("suggested_receivable",sa.Numeric(12,2),nullable=False),sa.Column("actual_receivable",sa.Numeric(12,2),nullable=False),sa.Column("expense_amount",sa.Numeric(12,2),nullable=False),sa.Column("track_participants",sa.Boolean(),nullable=False),sa.Column("requires_attendance",sa.Boolean(),nullable=False),sa.Column("status",sa.String(30),nullable=False),sa.Column("schedule_entry_id",sa.String(36),sa.ForeignKey("schedule_entries.id")),sa.Column("notes",sa.Text()),sa.Column("id",sa.String(36),primary_key=True),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.Column("version",sa.Integer(),nullable=False))
    op.create_table("event_participants",sa.Column("event_id",sa.String(36),sa.ForeignKey("temporary_events.id",ondelete="CASCADE"),nullable=False),sa.Column("student_id",sa.String(36),sa.ForeignKey("students.id"),nullable=False),sa.Column("attendance_status",sa.String(30)),sa.Column("id",sa.String(36),primary_key=True))
def downgrade()->None:
    for n in ["event_participants","temporary_events","venue_bookings","venue_price_rules"]:op.drop_table(n)
